### ISSUE TITLE
Drum Rack Mode

### ISSUE THREAD

**Issue by braindef** [hdavid/Launchpad_Pro95#4]
Hi David or Henri

Dein GIT-Account sagt dass Du von Deutschland bist also schreib ich mal deutsch...

Erst mal danke für das Tool und ich hätte einen kleinen Verbesserungsvorschlag:

Im Drum Rack Modus wärs toll, wenn beim Auswählen des Drum-Samples bei der 4x4 Matrix unten rechts der Drum irgendwie vorgehört werden könnte. Es geht zwar schon bei 4x4 Drum Racks, auf den Note-Modus des Launchpads selber zu wechseln und ihn da vorzuhören. Aber wenn das Drum Rack mehr als 4x4 Samples hat, dann hat man keine Ahnung wo man jetzt genau ist wenn man mit "Scale" Taste (die für "alles erste Szene"), deshalb wärs ganz toll wenn man da irgendwie mit der 4x4 Matrix unten links vorhören könnte (z.B. in dem man noch irgend eine weitere Taste gleichzeitig drückt)

Ich würds ja selber machen und dann ein Pull request, denn ich kann eigentlich recht gut python, aber da Du Dich mit Kommentaren im Code zürück hältst, hätte ich wirklich sehr lange bis ich da den Einstige gefunden hätte. Also hab ich gedacht ich mach einfach mal ein Issue auf :)

Ein Lieben Gruss aus der Schweiz
Marc

**Comment by hdavid** [comment]
from the manual :

**velocity (7th scene button)**:
hold velocity button and click on a note to change its velocity
***hold velocity button and click on a note to change in the note selector to ear a preview of the sound***
hold velocity button and select a loop range in the loop selector to extend the original clip content to the newly selected length


it is true manual could use some rewirting, but function is there.

**Comment by braindef** [comment]
Thank you :)
