### ISSUE TITLE
Help with my code?

### ISSUE THREAD

**Issue by Jonny0815** [hdavid/Launchpad_Pro95#6]
Hello

im trying to create my own remote script but my progress is rather slow, currently im having problems with converting a simple button to a toggle button, i found your code via google and you use the togglecomponent, however i cant transfer your solution to my problem, are you willing to give me a helping hand?

https://github.com/Jonny0815/mdcr/blob/master/mdcr.py
in line 57 im mapping the arm of the channel to a button on my bcf2000, ive configured the button on the device to be a toggle, but i cant make it work on the script

im usually a c++ coder and python drives me crazy, any help would be appreciated

**Comment by hdavid** [comment]
sorry, i dont have a BCF2000 to test with, so i wont be able to help :/
i hope you found a solution in the meantime
